apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-auth-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: main-auth-service
  template:
    metadata:
      labels:
        app: main-auth-service
    spec:
      containers:
      - name: main-auth-service
        image: emakeiv/main-auth-service
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
