apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-database
spec:
  selector:
    matchLabels:
      app: auth-service-database
  template:
    metadata:
      labels:
        app: auth-service-database
    spec:
      containers:
      - name: auth-service-database
        image: postgres:17
        imagePullPolicy: IfNotPresent
         resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432


