version: "3.8"

services:
  main-auth-service:
    build:
      context: ..
      dockerfile: .docker/app/dockerfile
    container_name: main-auth-service
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
